Fix type conversions between vector types
Build with GCC 11.1 was broken because of some implicit type conversions,
causing the compilation to fail with many errors like this:

$ pveclib/src/pveclib/vec_int128_ppc.h:4610:22: error: incompatible types when
assigning to type ‘vui128_t’ {aka ‘__vector(1) __int128 unsigned’} from type
‘vb128_t’ {aka ‘__vector(1) __int128’}
 4610 |               vsgn = vec_setb_sq (vra);
      |                      ^~~~~~~~~~~

Some of these were caused by testsuite wrappers with different signatures from
their inner functions and also some missing casts on the definitions of
vec_sraq, vec_sraqi, and vec_setb_ncq.

          * src/pveclib/vec_int128_ppc.h
          (vec_setb_ncq): Change 'result' type to vb128_t
          (vec_set_sraq): Cast output for vec_setb_sq to vui128_t
          * src/testsuite/vec_int128_dummy.c
          (test_setb_cyq, test_setb_ncq, test_setb_sq): Use vb128_t for the
          return type

Signed-off-by: Matheus Castanho <msc@linux.ibm.com>